version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "30004:30004"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "30001:30001"